### ISSUE TITLE
405 Client Error when placing order

### ISSUE THREAD

**Issue by RagnarHagberg** [Qluxzz/avanza#47] opened 2022-02-17 08:16 UTC
Placing an order does gives an error.
Error:
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://www.avanza.se/_api/order

URI: | /_api/order
Status: 405
Message: Request method 'GET' not supported

with this data:
           account_id="XXXXXXX",
           order_book_id=290011
           order_type=OrderType.SELL,
           price=79.6,
           valid_until=2022-02-17
           volume=1.0

**Comment by RagnarHagberg** [comment] 2022-02-17 14:44
The example to buy does not work either.
https://pypi.org/project/avanza-api/.

**Comment by RagnarHagberg** [comment] 2022-02-17 14:53
I got the same error but I wrote what was in the link. Avanza might have changed their API which would lead to this not working.

**Comment by AmirEghbali** [comment] 2022-02-17 14:55
It is possible to read prices etc but order placement does not work apparently today.

**Comment by Alexey-Klechikov** [comment] 2022-02-17 23:35
Hej guys. The fix for the issue is to replace an endpoint for order creation in the constants.py.
Row 96: "ORDER_PLACE_PATH = '/_cqbe/trading/order/new'" 

Could the author make a fix?

**Comment by tux2000** [comment] 2022-02-18 07:45
Fixed in my branch, see pull request...

**Comment by Alexey-Klechikov** [comment] 2022-02-18 07:54
Addition to my last comment to fix the order type - update avanza.py, 
Row 1528: " 'side': order_type.value," -

**Closed** 2022-02-18 11:02 UTC

**Comment by Qluxzz** [comment] 2022-02-18 12:29
I have published a new version, 3.0.1 which includes these changes.
